# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_binary_packages:
  - devtools
  - roxygen2

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
  - Rscript -e 'covr::codecov()'

after_failure:
  - Rscript -e 'devtools::test()'
