renv::activate()
renv::upgrade()

renv::install("magrittr")
renv::install("devtools")
renv::install("tidyverse")
renv::install("config")
renv::install("here")
renv::install("lifecycle")
renv::install("r-lib/usethis")
# renv::remove("usethis")

usethis::use_readme_rmd()
usethis::use_travis()
usethis::use_coverage()
usethis::use_lifecycle()

usethis::use_package("magrittr")
usethis::use_package("here")
usethis::use_package("config")
usethis::use_package("stringr")
usethis::use_package("fs")
usethis::use_package("devtools", type = "Suggests")

usethis::use_news_md()
usethis::use_testthat()
write(NULL, here::here("BACKLOG.md"))
write(NULL, here::here("config.yml"))

usethis::use_test("conf_get")
usethis::use_test("conf_load")
usethis::use_test("conf_assign")
usethis::use_test("conf_merge")
usethis::use_test("conf_has_inherited")
usethis::use_test("conf_resolve_inherited")
usethis::use_test("conf_merge_inherited")
usethis::use_test("conf_handle_inherited")
usethis::use_test("conf_has_config_reference")
usethis::use_test("conf_resolve_config_reference")
usethis::use_test("conf_handle_config_reference")
